spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: systemDB
    password:
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.formate_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false


